name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@HEAD
      - name: Compile LaTeX document
        uses: evanberkowitz/latex-action@master
        with:
          root_file: master.tex
